### ISSUE TITLE
Formatting of files containing @VARIABLE@ fails

### ISSUE THREAD

**Issue by yeganer** [cheshirekow/cmake_format#109]
Hey again,

I just tested the new version (0.5.0) and encountered an issue with formatting of cmake files expected to be run through a `configure_file` command. Specifically I have a Config.cmake.in file containing the template for the exported ProjectConfig.cmake file. This file contains the line
```
@PACKAGE_INIT@
```
which causes an error:
```
AssertionError: Unexpected UNQUOTED_LITERAL token at 1:0
```

EDIT: Maybe this didn't work before and I just noticed

**Comment by cheshirekow** [comment]
Ah, yeah, I haven't tried to address configure inputs yet. I'm pretty sure this wouldn't have worked before either. Honestly this hasn't even been on my radar but it's an interesting use case. 

Maybe I'll use this issue to track it as a feature request. The easiest path to support for configure inputs is to make `# cmake-format: off` bypass parsing altogether. This would also enable formatting of cmake code embedded in other files.

An alternative would be to try to understand the configure variable syntax but since these configure variables can have partial cmake code underneath it there's no way to reliably parse it. Then again, a lot of people probably have configure inputs which are syntactically valid except for the configure vars... So maybe we could just parse and ignore them.

**Comment by cheshirekow** [comment]
I am doing some planning for how best to implement this feature, I think that
probably there are a couple of things needed:

1. Add `@<word>@` token to lexer, and plumb through to the parser
2. Figure out how to notify the parser that a file is a "valid configure input" file.
3. We need something similar to `# cmake-format: off` that disables parsing all together

The need for (1) is obvious, we need to lex files containing these tokens.

The need for (2) is due to the fact that `@<word>@` is not a valid token outside
`configure_file`. For cmake-format this isn't really a problem, but for
cmake-lint it would be useful to identify when `@<word>@` tokens leak into
non-configured listfiles.

The complex solution, once we have a cmake indexer in place (planned) we can
lookup whether or not a file is possibly used in a `configure_file` command in
order to put it into "configure-file" mode. Some simpler solutions:

1. `--assume-in`: assume that the input file(s) are configure inputs. Allow 
   @-tokens and enable/disable some lint checks.
2. Require a sentinel comment somewhere near the top of the file 
  `# cmake-format: assume-in`

The need for (3) is due to the fact that the @-token might covers a range of 
syntactically important code (such as parentheses, or whole scope blocks). 
We'll need a way to help out the parser so that it skips these sections. 

The short term though is to just add the token definition so the parser doesn't 
choke on these tokens. That will likely enable the most common use cases. 

Please let me know if you have any thoughts.

**Comment by cheshirekow** [comment]
"at-words" are not understood by the lexer. This should allow you to format/lint any configured infiles provided that at-words are only used to replace single tokens.

**Comment by cheshirekow** [comment]
Thanks for the report. 

> provided that at-words are only used to replace single tokens.

which isn't true for the OP (and your case). I'll reopen the issue.

**Comment by kdopen** [comment]
Oddly enough - I just hit the same problem about 10 minutes ago. This time with cmake-lint. 

Possibly @PACKAGE_INIT@ throws the parser because it appears on it's own on a line (not in a string or as a command argument etc). It's probably the one ATWORD guaranteed to be in every `.in` file, too.

**Comment by henryiii** [comment]
Looking forward to this in the the next release, then! I just was trying to format a template file and ran into this.

**Comment by cheshirekow** [comment]
@henryiii are you experiencing problems with this in the latest release? I think it is fixed. There is even [a test][1].

[1]: https://github.com/cheshirekow/cmake_format/blob/master/cmake_format/command_tests/misc_tests.cmake#L887

**Comment by henryiii** [comment]
You are right! I was using 0.6.10 since that was the last version out for pre-commit, but now that I've updated to 0.6.11 (thanks for releasing that), this works!
