### ISSUE TITLE
Better handling of un-wrappable, too long lines

### ISSUE THREAD

**Issue by knatten** [cheshirekow/cmake_format#133]
If a line is too long to be wrapped, cmake-format currently crashes with an `IndexError`. For instance:
```cmake
message(FATAL_ERROR "Internal executable target ${ARG_NAME} specifies the QUALITY option. This option is only to be used for public executables.")
```
results in the following crash:
```
Traceback (most recent call last):
  File "cmake_format/__main__.py", line 480, in <module>
    sys.exit(main())
  File "cmake_format/__main__.py", line 444, in main
    outtext = process_file(cfg, intext, args.dump)
  File "cmake_format/__main__.py", line 121, in process_file
    box_tree = formatter.layout_tree(parse_tree, config)
  File "/home/knatten/code/cmake_format/cmake_format/formatter.py", line 1961, in layout_tree
    root_box.reflow(config, (0, 0))
  File "/home/knatten/code/cmake_format/cmake_format/formatter.py", line 389, in reflow
    outcursor = self._reflow(config, Cursor(*cursor), repass)
  File "/home/knatten/code/cmake_format/cmake_format/formatter.py", line 1769, in _reflow
    cursor = child.reflow(config, column_cursor, passno)
  File "/home/knatten/code/cmake_format/cmake_format/formatter.py", line 699, in reflow
    self._wrap = self._get_wrap(config, repass)
  File "/home/knatten/code/cmake_format/cmake_format/formatter.py", line 357, in _get_wrap
    algoid = config.algorithm_order[algoidx]
IndexError: list index out of range
```

It took quite a while to figure out what was the actual problem here. It would be better if it gave a descriptive message about the problem. ("Line <line> in <file> is <c> characters, which exceeds the maximum of <max> characters, and this line can't be automatically wrapped" or something like that.)

It's also interesting to consider what the behaviour should be here. Should it give up and print an error, or should it just leave lines it can't wrap alone and allow them to be too long?

Reproduced at 7a9c54f1.

**Comment by cheshirekow** [comment]
"Improve error messages for exceptions/assertions caused by malformed input" is on the [TODO list][1]. I understand it is a pain to figure out the underlying cause of the problem. A stack trace is really unhelpful in this situation.

As far what the behavior should be: In order to be a merge gate there is a clear (partial) answer: print an error and exit with non-zero exit code. 

As far as whether not to also write out a modified file? For now, I think it's better not to. For one, there are too many different cases for why it might fail to fit things into a given space. It might not be feasible to isolate "lines it can't wrap", so leaving them "unmodified" would be challenging. One possible alternative is that it could write out its best-effort formatting (the last, most aggressive attempt that was made). If you think you'd use that as a feature I'll tag this as a feature-request and put it in the TODO list. Personally, I would not enable that feature. If formatting fails the file is going to have to be touched anyway and I would rather things not move around while I'm editing to fix the issue. 

[1]: https://github.com/cheshirekow/cmake_format/blob/master/cmake_format/doc/todo.rst

**Comment by knatten** [comment]
Thanks for the reply! I hadn't noticed the TODO list.

Just exiting with a non-zero exit code sounds like a good option. Then the developer can manually split the line however they want. I don't think we need to complicate it more than that.

**Comment by cheshirekow** [comment]
I apologize. Digging in a little more this is an actual bug. Incidentally, it is already fixed. Furthermore, the current behavior actually is this:

> One possible alternative is that it could write out its best-effort formatting (the last, most aggressive attempt that was made).

I've added the code to exit with non-zero status if the layout failed but since that is not the current behavior I'm enabling it with the `--require-valid-layout` flag.
