### ISSUE TITLE
How can I use `--line-width` as `--max-line-width`?

### ISSUE THREAD

**Issue by aliha** [cheshirekow/cmake_format#146]
I would like to format lines and break them if they are longer than a threshold. 
But, I do not want to merge already wrapped lines.
For example,  
```
add_custom_target( coverage
    COMMAND ${CMAKE_COMMAND} ${arguments} 
    COMMENT "Execute code coverage and generate report"
    VERBATIM
)
```

I do not what the above format changes into (assuming `line_width = 150`):
`add_custom_target(coverage COMMAND ${CMAKE_COMMAND} ${arguments} COMMENT "Execute code coverage and generate report" VERBATIM)`

How can I configure cmake_format to achieve this goal?

**Comment by cheshirekow** [comment]
With version `0.6.0` and `--line-width=150` I'm getting something pretty close to what you want:
```
add_custom_target(
  coverage
  COMMAND ${CMAKE_COMMAND} ${arguments}
  COMMENT "Execute code coverage and generate report"
  VERBATIM)
```
So are you modifying any other settings?

> But, I do not want to merge already wrapped lines.

In general, this is not currently possible. `cmake-format` is a formatter, not an error-corrector. It has no concept of "leaving things as they were" because the formatter has no awareness of how things were. In order to be an "error-corrector" it would first have to implement an "error-recognizer", which is actually a planned goal. But until then, it's a formatter.

However you can, in-general, achieve what you want by inserting a blank line comment `#` after any line where you want to force it to wrap. So probably give that a try. By default `cmake-format` wont accept more than 2 lines of horizontal-wrapping so might need to put in two:

```
add_custom_target(
  coverage #
  COMMAND ${CMAKE_COMMAND} ${arguments} #
  COMMENT "Execute code coverage and generate report" VERBATIM)
```

Note that there is a bug in `0.6.0` where the formatting is not great if the line-comment is the very first thing (i.e. force-wrap the first argument).

**Comment by aliha** [comment]
Thank you for the very quick response @cheshirekow.
Using `#` can work. But, I need to go through the code manually and add `#`.

Is there any way to change the behaviour of `--line-width` to `--max-line-width`, similar to `ColumnLimit` in `clang-format`? 
If we can do that, would I get the expected format?

**Comment by cheshirekow** [comment]
I'm sorry, I don't understand the question. The current behavior of `--line-width` *is* similar to the `ColumnLimit` of `clang-format`. 

Can you be a bit more specific? As I mentioned, I'm unable to reproduce your original example so my best guess is that maybe your configuration isn't what you think it is. Did you maybe set `--line-width=1500` instead of `--line-width=150`? I'll repeat my original question:

> So are you modifying any other settings?

**Comment by aliha** [comment]
Thank you for the follow up and sorry for not being clear. 
I want to keep some of the manual formatting as is. (I assumed that the reason my manual formatting was changed by cmake_format was `line-width`, but I could be wrong).

My initial code was:
```
add_custom_target( coverage
    COMMAND ${CMAKE_COMMAND} ${arguments} 
    COMMENT "Execute code coverage and generate report"
    VERBATIM
)
```
Which was changed to a single line. 
So, the question is: What was the cmake_format configuration(s) caused that particular formatting change? Is there any way to prevent that change by changing a configuration (and not by manually adding `#`)

This is my config file: 
```
# --------------------------
# General Formatting Options
# --------------------------
# How wide to allow formatted cmake files
line_width = 150


# How many spaces to tab for indent
tab_size = 4

# If an argument group contains more than this many sub-groups (parg or kwarg
# groups), then force it to a vertical layout.
max_subgroups_hwrap = 5

# If a positinal argument group contains more than this many arguments, then
# force it to a vertical layout.
max_pargs_hwrap = 6

# If true, separate flow control names from their parentheses with a space
separate_ctrl_name_with_space = False

# If true, separate function names from parentheses with a space
separate_fn_name_with_space = False

# If a statement is wrapped to more than one line, than dangle the closing
# parenthesis on it's own line.
dangle_parens = False

# If the trailing parenthesis must be 'dangled' on it's on line, then align it
# to this reference: `prefix`: the start of the statement,  `prefix-indent`: the
# start of the statement, plus one indentation  level, `child`: align to the
# column of the arguments
dangle_align = 'prefix'

min_prefix_chars = 4

# If the statement spelling length (including space and parenthesis is larger
# than the tab width by more than this amoung, then force reject un-nested
# layouts.
max_prefix_chars = 10

# If a candidate layout is wrapped horizontally but it exceeds this many lines,
# then reject the layout.
max_lines_hwrap = 2

# What style line endings to use in the output.
line_ending = 'unix'

# Format command names consistently as 'lower' or 'upper' case
command_case = 'unchanged' # 'upper' #'canonical'

# Format keywords consistently as 'lower' or 'upper' case
keyword_case = 'unchanged'

# Specify structure for custom cmake functions
additional_commands = {
  "pkg_find": {
    "kwargs": {
      "PKG": "*"
    }
  }
}

# A list of command names which should always be wrapped
always_wrap = []

# If true, the argument lists which are known to be sortable will be sorted
# lexicographicall
enable_sort = True

# If true, the parsers may infer whether or not an argument list is sortable
# (without annotation).
autosort = False

# If a comment line starts with at least this many consecutive hash characters,
# then don't lstrip() them off. This allows for lazy hash rulers where the first
# hash char is not separated by space
hashruler_min_length = 10

# A dictionary containing any per-command configuration overrides. Currently
# only `command_case` is supported.
per_command = {}

# A dictionary mapping layout nodes to a list of wrap decisions. See the
# documentation for more information.
layout_passes = {}


# --------------------------
# Comment Formatting Options
# --------------------------
# What character to use for bulleted lists
bullet_char = '*'

# What character to use as punctuation after numerals in an enumerated list
enum_char = '.'

# enable comment markup parsing and reflow
enable_markup = False

# If comment markup is enabled, don't reflow the first comment block in each
# listfile. Use this to preserve formatting of your copyright/license
# statements.
first_comment_is_literal = False

# If comment markup is enabled, don't reflow any comment block which matches
# this (regex) pattern. Default is `None` (disabled).
literal_comment_pattern = None

# Regular expression to match preformat fences in comments
# default=r'^\s*([`~]{3}[`~]*)(.*)$'
fence_pattern = '^\\s*([`~]{3}[`~]*)(.*)$'

# Regular expression to match rulers in comments
# default=r'^\s*[^\w\s]{3}.*[^\w\s]{3}$'
ruler_pattern = '^\\s*[^\\w\\s]{3}.*[^\\w\\s]{3}$'

# If true, then insert a space between the first hash char and remaining hash
# chars in a hash ruler, and normalize it's length to fill the column
canonicalize_hashrulers = True


# ---------------------------------
# Miscellaneous Options
# ---------------------------------
# If true, emit the unicode byte-order mark (BOM) at the start of the file
emit_byteorder_mark = False

# Specify the encoding of the input file. Defaults to utf-8.
input_encoding = 'utf-8'

# Specify the encoding of the output file. Defaults to utf-8. Note that cmake
# only claims to support utf-8 so be careful when using anything else
output_encoding = 'utf-8'
```

**Comment by cheshirekow** [comment]
Ok so I think the two relevant config options for what you're looking at are the `line_width` and the maximum subgroups allowed for h-wrapping (`max_subgroups_hwrap`). You've set the line-width to 150 characters and you're telling cmake-format to allow h-wrapping (normal word-wrap) for up to 5 groups. Your example is 126 characters wide and is composed of only four groups:

```
add_custom_target(
  coverage # group 1
  COMMAND ${CMAKE_COMMAND} ${arguments} # group 2
  COMMENT "Execute code coverage and generate report" # group 3
  VERBATIM # group 4
)
```
Because 4 < 5 cmake-format is allowed to use h-wrapping and because 126 < 150 it all fits on one line. 

To better help you to find a suitable configuration, I think it would be helpful to understand *why* you think this:

```
add_custom_target( coverage
    COMMAND ${CMAKE_COMMAND} ${arguments} 
    COMMENT "Execute code coverage and generate report"
    VERBATIM
)
```

is better than this:

```
add_custom_target(coverage COMMAND ${CMAKE_COMMAND} ${arguments} COMMENT "Execute code coverage and generate report" VERBATIM)
```

By default, cmake-format thinks its better for two reasons:

1. Anything over 80 characters is too wide
2. Any more than 3 groups in the same "semantic stream" is too many 

But since you've changed both of those options, I'm not sure how to qualify that the formatting you like is "better" than the single-line format. My guess is that you probably want to keep `max_subgroups_hwrap` lower than 5. But if that's not what you want, you'll need to justify *why* it's better and then maybe we can figure out a configuration that gets you there.

**Comment by aliha** [comment]
Thank you @cheshirekow for the comprehensive answer. 
Now I understand better how cmake_format works. I do not have a strong feeling towards the current format of the code. So, for now, I take the consistent looking format that cmake_format generates :-)

**Comment by cheshirekow** [comment]
You're welcome. 

> , I take the consistent looking format that cmake_format generates :-)

That is my goal :). 

Please note that cmake-format is still considered unstable. I suggest that you pin the version you're using because updates are likely to cause some formatting changes which may clutter your code reviews. While that's probably true in general, I think that formatting changes are going to be more frequent until a 1.0 release. 

Also, one last note, I do hope to add some additional knobs to help style-sheriffs express what is "good" formatting for their teams. The current set of knobs is somewhat limited...
