### ISSUE TITLE
Contributing documentation

### ISSUE THREAD

**Issue by sergeyklay** [cheshirekow/cmake_format#150]
Current contributing link at section https://github.com/cheshirekow/cmake_format#developers is broken:

![image](https://user-images.githubusercontent.com/1256298/68695577-ffe0d200-0583-11ea-9492-679ec7077501.png)

Oftentimes open source projects place a `CONTRIBUTING` file (instead of website link) in the root directory. Here is a fine [example](https://github.com/puppetlabs/puppet/blob/master/CONTRIBUTING.md) from Puppet, [opensource.guide](https://github.com/github/opensource.guide/blob/master/CONTRIBUTING.md) from GitHub and [another one](https://github.com/phalcon/cphalcon/blob/be15afbd51ed3f141c07c6d6417d665ab9ccd558/CONTRIBUTING.md) from Phalcon Framework. I suggest to create such a file and add link to it to the documentation website.

See also [Setting guidelines for repository contributors](https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors)

---

Refs: https://github.com/cheshirekow/cmake_format/pull/149

**Comment by cheshirekow** [comment]
Thanks for pointing out the broken link. I don't want to add clutter to the root of the repo so I didn't add a capfile there like some projects do. In the link you provided it looks like github only supports a file literally named `CONTRIBUTING` and only in three exact directories in order to link to it on the project page. That's a bummer. It would be nice if I could specify an existing file in the project config. Oh well.

**Comment by cheshirekow** [comment]
Broken link is fixed and [docs are updated][1]

[1]: https://cmake-format.readthedocs.io/en/latest/contributing.html
