### ISSUE TITLE
vscode extension: add support for variable substitution in Args

### ISSUE THREAD

**Issue by forouher** [cheshirekow/cmake_format#177]
Currently my workspace settings file looks like this:

```json
    "cmakeFormat.args": [
        "--config-file=/path/to/workspace/.cmake-format"
    ]
```

That works, but it would be cooler if I could write instead:
```json
    "cmakeFormat.args": [
        "--config-file=${workspaceRoot}/.cmake-format"
    ]
```
Then I could check the settings.json into the repo and it would be portable. Unfortunately, this currently fails.

**Comment by cheshirekow** [comment]
Hm... I'm looking around for any vscode API to do this and it looks like it might not exist (e.g. [this bug][1] or [this bug][2]). I can't even find documentation for how to query the value of vscode variables to implement the substitution myself. 

Sorry, this probably wont happen until vscode implements the support needed :/. Please let me know if you think that there is actually an API that I am missing. I'm not super fluent in the vscode ecosystem. 

[1]: https://github.com/microsoft/vscode/issues/46471
[2]: https://github.com/Microsoft/vscode/issues/23738

**Comment by forouher** [comment]
Hi, thanks for looking into this!

Uhm, I got the inspiration from the clang-format extension. There it is possible to do this:

`clang-format.assumeFilename": "${workspaceRoot}/.clang-format"`

Their github project is this: https://github.com/xaverh/vscode-clang-format-provider
No idea how they pulled it off, though...

**Comment by cheshirekow** [comment]
Hm... ok thanks for the pointer. Looks like what they did is a [little hacky][1] and only replaces a couple of well known variables, but since there is no general solution (and given the age of those bugs, probably wont be any time soon), then I think we can do the same for the cmake-format extension. 

[1]: https://github.com/xaverh/vscode-clang-format-provider/blob/master/src/extension.ts#L144
