### ISSUE TITLE
Official docker image

### ISSUE THREAD

**Issue by silvioprog** [cheshirekow/cmake_format#179]
Hi.

It would be nice to provide an official Docker image (alpine-based?) with `cmake_format` tool. It would allow to create a shim script without installing anything in the primary OS, something like [ShellCheck VSCode extension](https://marketplace.visualstudio.com/items?itemName=timonwong.shellcheck) does with its Docker image, so the [CMake-Format extension](https://marketplace.visualstudio.com/items?itemName=cheshirekow.cmake-format) could use this idea too. :-) 

Thank you!

**Comment by cheshirekow** [comment]
Um... I'm not really sure this is a worthwhile endeavor. Would anyone really prefer a 450MB linux image? Given that the actual package is only 150kb? I mean if you really want a docker image heres a dockerfile you can use:

```
FROM ubuntu
RUN apt update && apt install python python-pip && pip install cmake-format
```

**Comment by silvioprog** [comment]
> Um... I'm not really sure this is a worthwhile endeavor. Would anyone really prefer a 450MB linux image?

Alpine image contains about only 3 MB. The shellcheck image contains only 4.69 MB for amd64. Using a container the cmake-format users don't need to know/understand Python if pip or other python-related problem happens.

> If it's a popular request I'm happy to put something on dockerhub, but I can't imagine that being a good solution for anyone's usecase.

When the shell-check author published his application at Docker hub he thought something like this, now [his image](https://hub.docker.com/r/koalaman/shellcheck-alpine/tags) contains more than one million of downloads. And it is very, very, **very** useful for any Linux user, even if the distribution doesn't contains a pip or any other package manager installed previously.

**Comment by cheshirekow** [comment]
How big is an Alpine image with python? And isn't shellcheck a single statically linked executable? Why would anyone install a docker image of that? 

It's a trivial ask so I'm happy to do it, but it strikes me as extremely silly.

**Comment by okainov** [comment]
>Why would anyone install a docker image of that?

In order to use it in any CI as separated step, for example? `docker run --rm -v /real/path:/code whatever-check:latest` is the most simple command one could run in CI nowadays and its only requirement is Docker and having the files on the filesystem. No need to worry about Python versions, no need to worry about other environment issues and so on.

In general seems like there are several approaches in the world - full decomposition (separate as much as you can, use separated images for separated tasks) and "one image to rule them all". I don't know what is the real-world distribution of those, but in any case, suggestion to install it manually in existing Docker image is valid only for the latter, who already have full-blown image with all the tools they need. But for someone who just wants to add new stage i.e. to Gitlab CI steps, it would be so much easy to start if it would be possible to write something like

```yaml
cmake_check:
  image: cheshirekow/cmake-format:1.2.3
  script:
    - cmake-format --check .
```

**Comment by cheshirekow** [comment]
> ~33-35 Mb https://hub.docker.com/layers/python/library/python/alpine/images/sha256-e1f90fa07d2e983c1b30af47a6ff07298e21f35aa6aae1b15a1dc18446dd54e7?context=explore

![image](https://user-images.githubusercontent.com/1309820/81118494-cf984180-8edd-11ea-8356-2412f00a856b.png)


> full decomposition (separate as much as you can, use separated images for separated tasks)

I've never seen that level of granularity. One image per task? That sounds horribly complicated. I can't imagine trying to compose overlays for build system generator, compiler, linker, archiver, build system, script interpreter, etc, etc, etc. 

> But for someone who just wants to add new stage i.e. to Gitlab CI steps

Well, if you're linting cmake files, you're using cmake. If you're using cmake, you are generating and executing a build system. Since human beings write cmake listfiles, I expect that a format check would be integrated into that build system (e.g. `make chkfmt`). 

Anyhow, can you point me to a dockerfile for alpine linux with python. I'll have a look at it.

**Comment by okainov** [comment]
Links get out-of date really quick. Just go to https://hub.docker.com/_/python?tab=tags and find the tag you need, click on it and you'll see the steps as well as size.

>Well, if you're linting cmake files, you're using cmake. If you're using cmake, you are generating and executing a build system. Since human beings write cmake listfiles, I expect that a format check would be integrated into that build system (e.g. make chkfmt).

Could be. However here is an alternative story:
I recently implemented a check in our CI and one of the main points was to run such quick and easy checks first in a lightweight environment, and do not trigger heavy build system at all if the formatting is not good. So instead of using our full-blown Docker image with all the build dependencies we run "pre-commit" checks in a small `python` image which requires nothing but the linters themselves. No cmake, no compiler, no nothing. Just building our build env Docker image would take longer than the whole pipeline in case if code style checks fail.

**Comment by cheshirekow** [comment]
Ok, well, [here you go I guess][1]. Let me know if it works for you. I'll try to setup automated builds in the future. 

[1]: https://hub.docker.com/repository/docker/cheshirekow/cmake-format/tags?page=1
