### ISSUE TITLE
dangle_parens is not working as intended.  

### ISSUE THREAD

**Issue by andrewwaldrum** [cheshirekow/cmake_format#32]
(using 0.3.6 on Ubuntu 14.04)  
While using json, python, or yaml config files or command line option the trailing parentheses of a multi-line source list is placed at the end of the last line no matter what the setting of dangle_parens.  I see no effect of this setting(perhaps a regression issue?).

**Comment by andrewwaldrum** [comment]
My command:
cmake-format --config-file ${CONFIG_PATH}/cmake_config.yaml ./CMakeLists.txt
I am very confident it is finding the cmake_config.yaml as other changes are reflected.  

[InputCMakeLists.txt](https://github.com/cheshirekow/cmake_format/files/1903380/InputCMakeLists.txt)
[Result.txt](https://github.com/cheshirekow/cmake_format/files/1903394/Result.txt)

Appended .txt to these so I could upload them:
[cmake_config.py.txt](https://github.com/cheshirekow/cmake_format/files/1903386/cmake_config.py.txt)
[cmake_config.yaml.txt](https://github.com/cheshirekow/cmake_format/files/1903387/cmake_config.yaml.txt)

**Comment by cheshirekow** [comment]
Ok yeah, I see what's going on. Looking at the unit tests the logic is that dangle_parens is only applied if the command arguments don't fit on a column. Here's an illustration of intended behavior:

A:
```
      some_long_command_name(longargname
                             longargname
                             longargname
                             longargname
                             longargname
                             longargname
                             longargname
                             longargname)
```
versus
B:
```
      if(foo)
        some_long_command_name(
          longargname longargname longargname longargname longargname
        )
      endif()
```

Because `A` all fits in one column after the command name, the paren is not "dangled". Whereas `B` got wrapped to a new line underneath the command. If I were to turn this issue into a feature request, it sounds like what you're looking for would be an additional level of dangling parens i.e. "always". I considered implementing it that way to begin with but felt like the closing paren would be too easy to miss for a reader. Consider below two possible implementations of `dangle_parens = 'always'`:

Option 1:
```
      some_long_command_name(longargname
                             longargname
                             longargname
                             longargname
                             longargname
                             longargname
                             longargname
                             longargname
      )
```
Option 2:
```
      some_long_command_name(longargname
                             longargname
                             longargname
                             longargname
                             longargname
                             longargname
                             longargname
                             longargname
                            )
```
To me, both of these have readability issues because it's hard for me to determine the "open" part of closing paren. If one of these is actually preferable to you, however, let me know which one you like and I can look into adding it as an option. 

I will note that your example case is a bit different than the canonical one I designed for. In your case the command name is very short so dangling parens might be oK. For example:

Option 1:
```
      short(longargname
            longargname
            longargname
            longargname
            longargname
            longargname
            longargname
            longargname
       )
```
Option 2:
```
      short(longargname
            longargname
            longargname
            longargname
            longargname
            longargname
            longargname
            longargname
           )
```

Though my personal interpretation is that neither of these are as readable. Maybe really the option here should be "don't dangle parens for single-column wraps with command names longer then X characters".

**Comment by andrewwaldrum** [comment]
"Always" dangling parens are desirable not so much for readability but for consistency so a user can comment out or remove any entry in that list without worrying they are removing the parentheses.  

I would like the second option but I know some people/codebases I have seen would prefer your first option as well.  Looking at clang-format configs I think there are many, many opinions on the best way to format anything.    

I like your tool a lot and it might become THE Thing as Cmake takes over (which seems to be happening). 
 Perhaps long term a regex based custom config option would let people satisfy themselves with the tiny details(For example I also would like the ability to put spaces INSIDE brackets so set(a) becomes set( a ) ).  A general config tool might take the pressure off you to make every little thing happen.  Just a thought.

**Comment by sum01** [comment]
I don't know if it's up to some vote, but I personally prefer option 1.

**Comment by cheshirekow** [comment]
@andrewwaldrum I think that optimizing for write-ability is often the wrong thing. That said, I'm not opposed to adding some options to move the closing parens to a new line regardless of context. @sum01 noted. When implemented, I'll add options for either case.

**Comment by andrewwaldrum** [comment]
You are awesome.
