### ISSUE TITLE
comment on it's own line gets moved to previous line

### ISSUE THREAD

**Issue by johannkoenig** [cheshirekow/cmake_format#33]
cmake-format 0.3.6

```
if(test)
  # comment about test_function
  test_function()
endif()
```
gets reformatted to:
```
if(test) # comment about test_function
  test_function()
endif()

```
Is there any way to keep the comment on it's own line? From the example this seems like it should be possible:
```
if(foo)
  if(sbar)
    # This comment is in-scope.
    add_library(foo_bar_baz
```

**Comment by cheshirekow** [comment]
What version of `cmake-format` are you using. With version 0.3.6 and this test file:
```
if(test)
# comment about test_function
test_function()
endif()
```
I get this output
```
if(test)
  # comment about test_function
  test_function()
endif()
```

**Comment by johannkoenig** [comment]
0.3.6 from pip on debian testing
```
$ cmake-format -v
0.3.6

```

**Comment by cheshirekow** [comment]
So this is somewhat "by design". You can avoid the comment getting pulled up (I believe) if you precede the comment line by one blank line. Something like this:

```
if(CMAKE_TOOLCHAIN_FILE)

# Add toolchain file to config string
```
if I recall correctly it has to do with how the parse step is implemented. I do recall at some point thinking about this case and deciding "two newlines to separate". If I recall correctly it might have been due to the case where cmake-format decides to move a long postfix comment to it's own line. In that case we want to understand that the comment originally described the statement before it. 

That said, I'm not sure it was really a great idea and might be worth revisiting.

**Comment by cheshirekow** [comment]
yeah, exactly!
