### ISSUE TITLE
Competing heuristics for 2+ argument statements that are one character short of fitting on a single line.

### ISSUE THREAD

**Issue by mikew-lunarg** [cheshirekow/cmake_format#51]
1. [# cmake-format: off](https://github.com/mikew-lunarg/cmake_stuff/blob/v040rc1/KhronosGroup/Vulkan-Loader/loader/CMakeLists.txt#L285) gets indented, the matching [# cmake-format: on](https://github.com/mikew-lunarg/cmake_stuff/blob/v040rc1/KhronosGroup/Vulkan-Loader/loader/CMakeLists.txt#L299) remains unindented.  Personally I prefer them both unindented as before.
1. This [set()](https://github.com/mikew-lunarg/cmake_stuff/blob/v040rc1/KhronosGroup/Vulkan-Tools/cube/macOS/cubepp/cubepp.cmake#L25) command is formatted very differently than other set() commands before and after.  Not clear why.

Thanks very much!

**Comment by cheshirekow** [comment]
Hm... on second thought, (1) is somewhat intentional. Whilte it may be possible to leave both unformulated it's a little confusing to think where in the stream of tokens we start/stop formatting. The way it is implemented now is "From the end of the `# cmake-format: off` token to the start of `# cmake-format: on` token, which is very straight forward to identify. My guess is that what you are requesting is something like: "From the end of the last `NEWLINE` token before the occurance of `# cmake-format:off` or the start of the file if there is none", which would preclude putting `# cmake-format: off` at the end of a statement. Not a terrible comprimise, but I'd have to think about that further if you'd like to make that a feature request. 

As for (2): I get this with python 2.7.12 and 3.5.2:

```
set(cubepp_SRCS
    ${CMAKE_CURRENT_SOURCE_DIR}/macOS/cubepp/main.mm
    ${CMAKE_CURRENT_SOURCE_DIR}/macOS/cubepp/AppDelegate.mm
    ${CMAKE_CURRENT_SOURCE_DIR}/macOS/cubepp/DemoViewController.mm)

set(cubepp_HDRS ${CMAKE_CURRENT_SOURCE_DIR}/macOS/cubepp/AppDelegate.h
    ${CMAKE_CURRENT_SOURCE_DIR}/macOS/cubepp/DemoViewController.h)

set(cubepp_RESOURCES ${CMAKE_BINARY_DIR}/staging-json/MoltenVK_icd.json
    ${CMAKE_CURRENT_SOURCE_DIR}/macOS/cubepp/Resources/LunarGIcon.icns)

```

**Comment by mikew-lunarg** [comment]
About (1): I can see your point.    However

`# cmake-format:` really isn't just a typical comment to be flowed with the rest.  it's an active command to the tool, more like a C pre-processor directive.  The broken symmetry between `# cmake-format: on` and `# cmake-format: off` is rather jarring.

Re (2):  I ran that formatting on Ubuntu LTS 16.04 with the following.  I can retry on other system configs in a couple days, see if the issue travels.
```
$ python --version
Python 2.7.12
$ python3 --version
Python 3.5.2
$ cmake --version
cmake version 3.5.1
```

**Comment by cheshirekow** [comment]
Yeah, I've got the same setup with ubuntu and python, and still get that formatting. I tried that with stdout as output and with `-i` and got it both times. My guess is maybe if you were running v0.4.0rc1 through the environment PYTHONPATH maybe the environment was cleared for that file or something?

Can you paste the command you used? I'll see if I can replicate the behavior.

**Comment by mikew-lunarg** [comment]
Ok, I've tried it on Ubuntu and Windows, 0.4.0rc1 and 0.4.0, pip-installed and tarball.

I consistently get the same weird formatting on that set() command, on every tested platform with 0.4.0.

My 0.4.0* results are all identical, see [1](https://github.com/mikew-lunarg/cmake_stuff/blob/test2_040rc1_ubuntu1604/KhronosGroup/Vulkan-Tools/cube/macOS/cubepp/cubepp.cmake#L25) [2](https://github.com/mikew-lunarg/cmake_stuff/blob/test2_040_ubuntu1604/KhronosGroup/Vulkan-Tools/cube/macOS/cubepp/cubepp.cmake#L25) [3](https://github.com/mikew-lunarg/cmake_stuff/blob/test2_040_win10/KhronosGroup/Vulkan-Tools/cube/macOS/cubepp/cubepp.cmake#L25)

I appreciate you're not able to repro mine, but I'm not able to repro yours!

My 0.4.0* tests all begin with the 0.3.6 baseline, as shown in my git history.  Here are the invocation scripts I used in each test.  (The 0.3.6 is slightly different, to workaround the comment bug)...
* [Baseline 0.3.6 pip on Ubuntu](https://github.com/mikew-lunarg/cmake_stuff/blob/test2_036/FORMAT.sh)

These 0.4.0* are all basically identical...
* [0.4.0rc1 tarball on Ubuntu](https://github.com/mikew-lunarg/cmake_stuff/blob/test2_040rc1_ubuntu1604/FORMAT.sh)
* [0.4.0 tarball on Ubuntu](https://github.com/mikew-lunarg/cmake_stuff/blob/test2_040_ubuntu1604/FORMAT.sh)
* [0.4.0 pip on Windows 10 w git bash](https://github.com/mikew-lunarg/cmake_stuff/blob/test2_040_win10/FORMAT.sh)

**Comment by mikew-lunarg** [comment]
Trying another platform, I also get the same consistently weird formatting w 0.4.0 pip on [Raspbian](https://github.com/mikew-lunarg/cmake_stuff/tree/test2_040_raspbian).
(on a Pi Zero.  Had to try it ;-)

**Comment by cheshirekow** [comment]
The difference in behavior is apparently due to your `.cmake-format.py`. If I use your config file I'm able to reproduce (previously tested the file in isolation with default config). Now that I can reproduce, I can try to figure out whats going on.

**Comment by cheshirekow** [comment]
Ok, so note that `    cubepp_HDRS ${CMAKE_CURRENT_SOURCE_DIR}/macOS/cubepp/AppDelegate.h ${CMAKE_CURRENT_SOURCE_DIR}/macOS/cubepp/DemoViewController.h` is exactly 132 characters wide (your configured column limit). So that is what leads to the slight weirdness of the dangling paren, however the formatting:

```
set(cubepp_HDRS 
    ${CMAKE_CURRENT_SOURCE_DIR}/macOS/cubepp/AppDelegate.h
    ${CMAKE_CURRENT_SOURCE_DIR}/macOS/cubepp/DemoViewController.h)
```
Should be the preferred formatting. I'm not sure why it's passing over that one. I'll update when I figure out what's going on.

**Comment by cheshirekow** [comment]
Ok, I see the problem. It has to do with the fact that everything "almost" fits on one line. It is just one character short. There are two heuristics that come into play in this situation and they seem to conflict. 

Note to self for how to fix:
1. HPACking single arguments doesn't account for the extra character required for the RPAREN
2. RPAREN is not dangled in VPACK for a statement. The idea was that if it would overflow we should go to NVPACK next instead of dangling.

**Comment by cheshirekow** [comment]
As a temporary workaround, I suggest adding a blank comment at the end:
```
set(cubepp_HDRS
    ${CMAKE_CURRENT_SOURCE_DIR}/macOS/cubepp/AppDelegate.h
    ${CMAKE_CURRENT_SOURCE_DIR}/macOS/cubepp/DemoViewController.h #
    )
```
