### ISSUE TITLE
Sort files

### ISSUE THREAD

**Issue by notzain** [cheshirekow/cmake_format#78]
Just found this tool, it's absolutely amazing. One thing I'd like added is sorting files.

Suppose the following:
```cmake
set(SOURCES
    folder_b/source_a.cc
    folder_a/source_a.cc
    source_a.cc
    source_c.cc
    source_b.cc)
```

into

```cmake
set(SOURCES
    folder_a/source_a.cc
    folder_b/source_a.cc
    source_a.cc
    source_b.cc
    source_c.cc)
```

**Comment by cheshirekow** [comment]
I would love this feature too :). It's planned, hopefully added soon.

**Comment by cheshirekow** [comment]
Just FYI: took a quick stab at this. I think the best solution will require a refactoring of the command specification which will require more than a quick day's work. I wrote down some implementation notes in `todo.rst`. This wont be in the next release but will hopefully be added soon.

**Comment by cheshirekow** [comment]
Just a heads up that I have a working prototype of this feature coming down the pipe:
```
  def test_add_library_sort(self):
    self.do_format_test("""\
      add_library(foo foo.cc bar.cc)
      """, """\
      add_library(foo foo.cc bar.cc)
      """)
    self.config.sort_filelists = True
    self.do_format_test("""\
      add_library(foo foo.cc bar.cc)
      """, """\
      add_library(foo bar.cc foo.cc)
      """)
```

**Comment by cheshirekow** [comment]
One thing I just noticed, is that in your example you use the `set()` command. In my current implementation, I'm able to label some argument lists as "list of files" because that is what the command expects (i.e. for `add_library()`). For `set()` however, there's no real way to *KNOW* whether or not the particular list of argument is sortable. For example:
```
set(libraries_to_link_ foo bar baz)
```
is definitely not something we want to sort. In otherwords `set()` is a pretty challenging case. What do you think about using a comment annotation to indicate that a list should be sorted (in the event that sort-ability is not implied by the commands semantics). For example:

```
set(SOURCES
    # cmake-format: sortable
    folder_a/source_a.cc
    folder_b/source_a.cc
    source_a.cc
    source_b.cc
    source_c.cc)
```

or something like that?

**Comment by notzain** [comment]
After a bit of quick googling, it seems that several articles/tutorials on cmake are split evenly on adding files using `set` vs `add_*`. So I don't think this usecase is too far-fetched.

I'm not sure how desirable it is for your other users to have tool-specific comment annotations in their cmake files; I personally have no problems with it. Also seems useful if it can be used inside any function.

Another solution could be a user-defined list of cmake variables to sort?
```
sorted_variables = ["SOURCES", "HEADERS"]
```

```cmake
set(libraries_to_link ... )     <-- don't sort
set(SOURCES ... )              <-- sort
set(HEADERS ...)               <-- sort
```

Personally, I'm fine with either comment annotations, config, or even only support on `add_*` functions.

**Comment by cheshirekow** [comment]
> So I don't think this usecase is too far-fetched.

Oh I totally agree. I've used this pattern myself in several places. It's particularly convenient when chaining together custom commands because you can use the same variable to specify the outputs of one custom command and then dependencies of another.

> I'm not sure how desirable it is for your other users to have tool-specific comment annotations in their cmake files;

I understand the hesitation, but I think it's somewhat of an inevitability. We already have `# cmake-format: off` and `# cmake-format: on` so I think the need for *some* annotations is pretty clear. I think it's an worthwhile goal to preclude tool specific annotations where possible... but I'm much more willing to make that compromise than compromising correctness. 

That said, I kind of like your idea of `sorted_variables`. It makes `set()` somewhat of a "special" function though, and the mechanism doesn't really extend to other commands which *may* be sortable depending on context. The annotation implementation enables argument sorting for new commands that `cmake-format` learns about through `additional_commands`. Consider, for example, custom commands implementing code generators (i.e. `protobufs`) or sidecar compilers (i.e. `nvcc/cuda`). Also, I can imagine that for a very large project the `sorted_variables` option can be problematic as some of those variable names may be used in a "sortable" context in some listfiles and an "unsortable" context in others. 

Then again, `set()` *is* pretty special, so treating it specially isn't necessarily a problem, and this is a good, simple solution which would enable fast refactoring for existing projects where it would work.

I'll think about it a little more before release, but given that `# cmake-format: sortable` is a more general solution (and I've already implemented it) I suspect I'll keep it. I might still implement `sorted_variables`, or at least `TODO` it for later. I think it's a good solution for small projects, but I'd like to noodle it over some more.

**Comment by cheshirekow** [comment]
I've pushed version `0.5.0` which includes automatic sorting of `add_library` and `add_executable`. `set()` can be sorted if tagged (see info in the readme). I'm going to close this issue but I've still got a TODO to think about implementing `sorted_variables`.
